# Generated by Django 3.2 on 2021-04-24 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Esportwebsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tb_news',
            new_name='tb_esportnews',
        ),
    ]
