# Generated by Django 3.2 on 2021-04-24 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Esportwebsite', '0002_rename_tb_news_tb_esportnews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tb_esportnews',
            new_name='tb_news',
        ),
    ]
