# Generated by Django 3.2 on 2021-04-26 01:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Esportwebsite', '0003_rename_tb_esportnews_tb_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_news',
            name='news_detail',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
