# Generated by Django 3.2 on 2021-04-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Esportwebsite', '0004_alter_tb_news_news_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_news',
            name='news_author',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
