# Generated by Django 3.2 on 2021-04-16 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Esportwebsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_news',
            old_name='news_datail',
            new_name='news_detail',
        ),
    ]
